### ISSUE TITLE
Folder selection does not work

### ISSUE THREAD

**Issue by smiley-94** [clegallic/MMM-GoogleDriveSlideShow#1]
when I leave rootFolderId to null, everything works fine, but if I try to write "smartMirrorPhotos" wich should be my main folder, it doesn't work any idea what I do wrong?

**Comment by smiley-94** [comment]
also, how do I delete the cache?
i set the cache to refreshDriveDelayInSeconds: 240,
and deleted a picture one hour ago, I still see it in the slideshow

**Comment by clegallic** [comment]
Hi Smiley

For rootFolderId, you have to use the folderId, not the folder name.
You can get the folderId by opening the folder in Google Drive in your browser. The folderID is the last part of the URL. 
For example : for **https://drive.google.com/drive/u/0/folders/0CxRVHnEINH-ZWGlPS2otNklmMWM**, the folderId is **0CxRVHnEINH-ZWGlPS2otNklmMWM**

To delete the cache, juste delete the **.cache** file in the root folder of the module 

Regards
