### ISSUE TITLE
RootFolderID

### ISSUE THREAD

**Issue by ndavaul** [clegallic/MMM-GoogleDriveSlideShow#2]
What are the options for RootFolderID?    How does one find out what the FolderID's are for each of the albums?

**Comment by clegallic** [comment]
Hi,

You can get the folderId by opening the folder in Google Drive in your browser. The folderID is the last part of the URL.
For example : for https://drive.google.com/drive/u/0/folders/0CxRVHnEINH-ZWGlPS2otNklmMWM, the folderId is **0CxRVHnEINH-ZWGlPS2otNklmMWM**.

If set to **null**, all images from your Google Drive will be grabbed.

You can check another answer here : https://github.com/clegallic/MMM-GoogleDriveSlideShow/issues/1#issuecomment-621034026

Regards,

Charles
