### ISSUE TITLE
Locks during npm install

### ISSUE THREAD

**Issue by emrahaslan** [clegallic/MMM-GoogleDriveSlideShow#4]
Hi , I tried to git clone this module, But I failed during npm-install , It shows no progress.

The screen says 

![image](https://user-images.githubusercontent.com/54321532/92996865-80ab8a00-f517-11ea-9f9c-cd2e2015ebe6.png)

**Comment by clegallic** [comment]
Hi

Can you check your NodeJS version ?

The module has been tested with versions `8.16.2` and `10.17.0`

You can also try to remove the `node_module` folder into the `MMM-GoogleDriveSlideShow` folder an retry.

**Comment by clegallic** [comment]
Closed due to inactivity
