### ISSUE TITLE
Fails when attempting to generate a token

### ISSUE THREAD

**Issue by alionoide** [clegallic/MMM-GoogleDriveSlideShow#5]
Log as follows:
```
 npm run token:generate

>  mmm-googledriveslideshow@0.0.1 token:generate /home/pi/MagicMirror/modules/MMM-GoogleDriveSlideShow
>  node generate-auth-token.js

/home/pi/MagicMirror/modules/MMM-GoogleDriveSlideShow/generate-auth-token.js:32
  const { client_secret, client_id, redirect_uris } = credentials.installed;
          ^

TypeError: Cannot destructure property `client_secret` of 'undefined' or 'null'.
    at fs.readFile (/home/pi/MagicMirror/modules/MMM-GoogleDriveSlideShow/generate-auth-token.js:32:67)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmm-googledriveslideshow@0.0.1 token:generate: `node generate-auth-token.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mmm-googledriveslideshow@0.0.1 token:generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-09-30T18_10_34_931Z-debug.log
```

Complete log: 
[2020-09-30T18_10_34_931Z-debug.log](https://github.com/clegallic/MMM-GoogleDriveSlideShow/files/5307632/2020-09-30T18_10_34_931Z-debug.log)

**Comment by clegallic** [comment]
Hi

It seems that your credentials JSON file is missing or badly formatted.
Could you check step 8. of the installation procedure in the README file and ensure that the credentials.jon file is in the « secrets » folder of the module, and also that it is filled with the client_secret and the client_id infos ?

Regards
Charles

**Comment by alionoide** [comment]
Can confirm that "credentials.json" is in the secrets folder. 
It also appears that the client_secret and client_id are in that file.
Here is a censored version of the contents of that file:
```
{"web":{"client_id":"############-xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com","project_id":"info-board-images","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"xxxxxxxx-xxxxxxxxxxxxxxxx"}}
```

**Comment by alionoide** [comment]
I seem to have found the issue on another similar module, the problem is that I didn't select "other" when generating the key.
However it also appears that there is no longer an "other" option. Am I doing something wrong or did they get rid of the "other" as an application type?
![NoOther](https://user-images.githubusercontent.com/72161334/94849443-0b7ef680-03eb-11eb-8cf1-0e7624d23773.PNG)
Edit: Image

**Comment by alionoide** [comment]
I looked into it a little more, after some trial and error I found that "Desktop app" as the application type works with no errors.
